
PICARDPATH=$1
INPUTFILE=$2
OUTPUTFILE=$3

java -XX:+UseSerialGC -jar ${PICARDPATH} MarkDuplicates \
        INPUT=${INPUTFILE} \
	METRICS_FILE=${OUTPUTFILE}.dedupMetrics \
        OUTPUT=${OUTPUTFILE} \
	MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 \
	OPTICAL_DUPLICATE_PIXEL_DISTANCE=10 \
	CREATE_INDEX=true	
