
PICARDPATH=$1
INPUTFILE1=$2
INPUTFILE2=$3
OUTPUTFILE=$4


java -XX:+UseSerialGC -jar ${PICARDPATH} MergeSamFiles \
	INPUT=${INPUTFILE1} \
	INPUT=${INPUTFILE2} \
	OUTPUT=${OUTPUTFILE} \
	CREATE_INDEX=true \
	SORT_ORDER=coordinate 

